apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: kruise-rollout
  namespace: default
spec:
  interval: 5m0s
  timeout: 1m0s
  url: https://openkruise.github.io/charts/
